title: Data Science Projects
author: Eugene Olkhov
email: eugeneolkhov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Data Science Projects

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
